#!/bin/bash

set -e
LANG=en_US.utf8
LOG_INFO()
{
    local content=${1}
    echo -e "\033[32m[INFO][chain33] ${content}\033[0m"
}

LOG_ERROR()
{
    local content=${1}
    echo -e "\033[31m[ERROR][chain33] ${content}\033[0m"
}

Download()
{
    local url=${1}
    local file=$(basename ${url})
    if [ ! -e ${file} ]; then
        curl -LO ${url}
    fi
}

# Download
LOG_INFO "Download solc ..."
Download https://github.com/ethereum/solidity/releases/download/v0.4.24/solc-static-linux

LOG_INFO "Download chain33 ..."
Download https://github.com/33cn/plugin/releases/download/v1.66.2/chain33-darwin-amd64.tar.gz

tar -zxf chain33-darwin-amd64.tar.gz
mv  chain33-darwin-amd64 chain33
mv  chain33-cli-darwin-amd64 chain33-cli
cp chain33.toml chain33-solo.toml

#[consensus]
##共识名,可选项有solo,ticket,raft,tendermint,para
#name="solo"

./chain33 -f chain33-solo.toml

